### ISSUE TITLE
Propose a CLI to sync a project with a tenant CMS pages

### ISSUE THREAD

**Issue by quentinovega** [MAIF/daikoku#486]
- [x] daikoku-cli --init 
  - add tenant domain
  - add personnal token
  - add other conf ? (pattern for blocks directory...)
- [x] daikoku-cli --fetch to sync and sync or create all file in project (if change in progress --force to overwrite ?)
- [x] sync files (path & content-type)
- [x] add a .daikokuignore (& use .gitignore) to not sync some files (ex: node_module or file use for js build)
- [x] daikoku-cli --deploy to push all sync files into tenant
- [x] daikoku-cli --watch to avoid fetch & deploy
- [ ] ~~use it to write a VsCode & intelliJ extension ?~~

**Comment by quentinovega** [comment]
close with https://github.com/MAIF/daikoku/pull/643
