### ISSUE TITLE
use team.authorizedOtoroshiGroups 

### ISSUE THREAD

**Issue by quentinovega** [MAIF/daikoku#600]
this property seems like intersting but never used somewhere
with a good UI to limit the scope to a team, a team could create safelly API in Daikoku

- [x] better form entry for AuthorizedEntities (maybe update react-forms for this. one entry, one otoroshi and disable add btn when all oto are setup)
- [x] Filter entities in UI (api usage plan)
- [x] idem ApiGroups
- [x] Control entities in backend
- [x] update swagger
- [x] update documentation
- [x] add tests
