### ISSUE TITLE
Better admin APIS - part II

### ISSUE THREAD

**Issue by quentinovega** [MAIF/daikoku#624]
## Context

The admin API exposes a generic `deleteEntity` endpoint for all entity types:

```scala
def deleteEntity(id: String): Action[AnyContent] =
  DaikokuApiAction.async { ctx =>
    if (ctx.request.queryString.get("logically").exists(_.contains("true")))
      entityStore(ctx.tenant, env.dataStore).deleteByIdLogically(id)
    else
      entityStore(ctx.tenant, env.dataStore).deleteById(id)
  }
```

This bypasses all cascade logic defined in `DeletionService` and `QueueJob`, leaving orphaned references in the database:
- Deleting an API via admin API → usage plans, subscriptions, Otoroshi keys, and third-party payment entries remain
- Deleting a usage plan → subscriptions remain active
- Deleting a user → team memberships remain (see related orphan issue)

The regular application routes correctly use `DeletionService` → `QueueJob` for cascade processing. The admin API does not.

## Proposed approach

Two complementary implementations are proposed:

---

### Option A — Cascading deletes via admin API

Route admin API deletions through the existing `DeletionService` instead of calling the repository directly.

Cascade chain per entity type:

**API deletion:**
1. Disable all subscriptions (set `enabled = false`)
2. Delete all subscriptions → sync with third-party payment provider (Stripe etc.)
3. Disable API keys in Otoroshi
4. Delete all usage plans
5. Delete API posts, issues, documentation pages
6. Soft-delete the API

**Usage plan deletion:**
1. Delete all subscriptions to the plan → sync with third-party payment provider
2. Disable API keys in Otoroshi for those subscriptions
3. Remove plan from API's `possibleUsagePlans`
4. If payment settings exist → trigger third-party product deletion
5. Soft-delete the plan

**User deletion:**
1. Remove user from all team `users` arrays
2. Delete personal team → cascade to owned APIs
3. Delete user subscriptions
4. Clear user sessions
5. Soft-delete the user

The existing `QueueJob` operation system should be reused for async steps (Otoroshi sync, payment provider calls).

The admin API should return a `202 Accepted` with an operation ID when deletion is queued asynchronously, rather than a synchronous `200 Ok`.

---

### Option B — Integrity check endpoint + remediation protocol

Add a dedicated endpoint that detects orphaned references and returns a structured report with the steps needed to fix them, leaving the actual cleanup to the operator.

```
GET /api/admin/integrity-check
```

Response:
```json
{
  "orphanedTeamMembers": [
    { "teamId": "...", "teamName": "...", "userId": "..." }
  ],
  "orphanedSubscriptions": [
    { "subscriptionId": "...", "reason": "api_deleted", "apiId": "..." },
    { "subscriptionId": "...", "reason": "plan_deleted", "planId": "..." }
  ],
  "danglingOtoroshiKeys": [
    { "subscriptionId": "...", "clientId": "...", "otoroshiSettingsId": "..." }
  ],
  "summary": { "total": 12, "critical": 3 }
}
```

A companion endpoint can trigger the remediation:
```
POST /api/admin/integrity-check/fix
```
This would queue the appropriate operations via the existing `QueueJob` system.

---

## Recommendation

Both options are complementary:
- **Option A** prevents orphans from being created via the admin API
- **Option B** handles orphans already present (from past admin API usage, direct DB edits, or failed queue jobs)

Option B also overlaps with the startup cleanup routine proposed in the orphan cleanup issue.

## Acceptance criteria

- [ ] Admin API delete routes go through `DeletionService` cascade logic (Option A)
- [ ] Async deletions return `202 Accepted` with an operation reference
- [ ] `GET /api/admin/integrity-check` reports all orphaned references (Option B)
- [ ] `POST /api/admin/integrity-check/fix` queues remediation via `QueueJob`
- [ ] No regression on existing admin API behavior for non-delete operations
- [ ] Existing cascade logic in `DeletionService` / `QueueJob` is not duplicated
